---
title: "to do list"
subtitle: "ASSIGNMENTS AND ALL THAT JAZZ"
date: today
format: 
  html:
    toc: true
    toc-location: right
    toc-depth: 6
    toc-float: true
    toc-expand: true
    toc-title: "**CONTENTS**"
    output-file: "to_do_list.html"
    # embed-resources: true
    # code-fold: true
    code-link: true
    code-tools: true
    # number-sections: false
    # bibliography: ./bib/ref.bib
    fontsize: "10"
    mainfont: "Helvetica"
    monofont: "Fira Code"
    # fontcolor: ""
    page-layout: article
    code-overflow: wrap
    df_print: paged
    theme: cosmo
    code-line-numbers: false
    grid:
      margin-width: 250px
crossref:
  fig-title: Figure     # (default is "Figure")
  tbl-title: Table     # (default is "Table")
  title-delim: "—"     # (default is ":")
  fig-prefix: Fig.     # (default is "Figure")
  tbl-prefix: Table.   # (default is "Table")
editor_options: 
  chunk_output_type: console
execute:
  warning: false
  message: false
  tidy: true
bibliography: references.bib
---

This thing is getting too long. And some of the basic concepts need clearer illumination. The scaling and nesting of unit of replication, sample size, and thus presentation. Summaries across space/individuals vs temporal vs spatiotemporal...Gah. 

BUT if htis becomes too long it becomes daunting for anyone to look at. We want this to be a tutorial aimed for beginners but also oldtimers...

# To-do / questions:

- [ ] Should we cover lnCVR? especially vs lnVR? In the appendix or its own section?

- [ ] Better names for effect size categories?

- [ ] I naturally code in data.table but maybe I should rewrite to base R or evil dplyr?

- [ ] Should we have more info on the basic details of extraction or is that too newbie?

- [ ] Figure out overdispersed lnRoM/SMD * missing error bar shit...SO CONFUSING...

**EJL**:

- [ ] Clarify framinig: "most of the examples in this tutorial come from ecology and evolution, where heterogeneous methodologies are rampant. However, we think this tutorial is useful for anyone doing a meta-analysis"

- [ ] Add experimental warning to the simulation extractions

- [ ] Heading structures on challenges pages

- [ ] Negative binomial

- [ ] Split assumptions into separate pages

- [ ] Email Wolfgang to invite to paper and also about paired SMD?

- [ ] Add section names

- [ ] Fix kable outputs...

- [ ] convert_effect_sizes() 

  - [ ] Use examples that Borenstein gives to double check function?

- [ ] Add equation for Var(d) from g and vice versa

- [ ] Chat with Shinichi about binomial question

- [ ] Full-width rendering of kables


Tasks

- [ ] SMD - Santi + Iwo

- [ ] lnOR - Kyle + Josh

- [ ] Zr - Ed + Christine

- [ ] Figures/flowcharts - Ayumi

- [ ] Logo - ???

- [ ] `escalc` cheatsheet - me?

- [ ] Conversions - me

- [ ] References - me

- [ ] Links - me

- [ ] Making sure language is clear and plain - Anna??

- [ ] Double-checking everything - Shinichi + Losia


# Thoughts/notes/questions

Should we give extraction challenges monikers? This could facilitate reporting, etc.

