---
title: "`escalc` cheatsheet"
subtitle: "so many estimators, so little time"
date: "`r Sys.Date()`"
format: 
  html:
    toc: true
    toc-location: right
    toc-depth: 6
    toc-float: true
    toc-expand: true
    toc-title: "**CONTENTS**"
    output-file: "escalc_cheatsheet.html"
    # embed-resources: true
    # code-fold: true
    code-link: true
    code-tools: true
    # number-sections: false
    # bibliography: ./bib/ref.bib
    fontsize: "10"
    mainfont: "Helvetica"
    monofont: "Fira Code"
    # fontcolor: ""
    page-layout: article
    code-overflow: wrap
    df_print: paged
    theme: cosmo
    code-line-numbers: false
    grid:
      margin-width: 250px
crossref:
  fig-title: Figure     # (default is "Figure")
  tbl-title: Table     # (default is "Table")
  title-delim: "—"     # (default is ":")
  fig-prefix: Fig.     # (default is "Figure")
  tbl-prefix: Table.   # (default is "Table")
editor_options: 
  chunk_output_type: console
execute:
  warning: false
  message: false
  tidy: true
bibliography: references.bib
---

```{r}
#| eval: true
#| echo: false
#| out-width: "70%"

rm(list = ls())
library("metaDigitise")
library("ggplot2")
library("gt")
library("lubridate")
library("data.table")
library("ggpattern")
library("patchwork")
library("metafor")
library("dplyr")
library("broom")
library("broom.mixed")
library("simplermarkdown")
library("crayon")

# Source our custom functions:
source("scripts/functions/eff_size.R")
source("scripts/functions/convert_effect_sizes.R")

```

`escalc` contains a bewildering number of effect size estimators. We here provide some information on alternative estimators for the main effect size types so far covered in this tutorial. We conclude by recommending preferred estimators for other designs, including single group effect sizes (e.g., proportions). Note we do not discuss effect size estimators that are not recommended for use in ecology and evolution, such as raw correlation coefficients or unstandardized mean difference.

# SMD and lnRoM options

*I wrote this when i thought these alternative formulations were comparable with SMD. Now that I know they are not, I'm not sure about having this here...Might move to appendix*

The standard estimators for SMD are "SMD" and "SMDH", the latter of which is for heteroscedastic data. The standard estimators for lnRoM are "ROM". There is no heteroscedastic estimator for lnRoM. This table includes alternative estimators provided by escalc and whether they are comparable to the standard estimator (either SMD, SMDH, or ROM). Note that paired design estimators require an additional input `ri`, an estimate of correlation between groups and take a single sample size (`ni`) instead of a sample size for two groups (`n1i`, `n2i`)


| class | `escalc` | Heteroscedasticity | Paired designs | Comparable to standard? |Details |
|-------|----------|--------------------|----------------|-------------------------|--------|
| SMD    | "SMCC"   | No                 | Yes | No  | Paired group formulation that uses the standard deviation of group 1 and 2. |
|       | "SMCR"   | No                 | Yes | No | Paired group formulation that uses standard deviation of group 1 only. |
|       | "SMCRH"  | Yes                | Yes | No | Same as above but for heteroscedastic data. |
|       | "SMCRP"  | No                 | Yes | No | An alternative formulation that uses the standard deviations of both group 1 and 2. |
| lnRoM | "ROMC"   | No                 | Yes | Yes | Paired formula for lnRoM. |

Note that "Zmu" is only available in our own function `eff_this` (originally published in Nakagawa et al. XXXX) and supplied here. To select a paired formula, set paired_design = TRUE and be sure to provide `r` and `n` as an input.

**Look into this:** "See also Morris and DeShon (2002) for a thorough discussion of the difference between the "SMCC" and "SMCR" change score measures"

**Not sure when you should use SMCC versus SMCRP** **I don't think any of them are compatible with SMD unpaired...Gahhh**

# lnOR / lnRR options

The standard estimator options in `escalc` are "OR" for lnOR and "RR". The alternative estimators below are for "matched pairs contingency tables". 

| class | `escalc` | Paired designs | Comparable to standard? | Details                    |
|-------|----------|----------------|-------------------------|----------------------------|
|lnOR   | "MPOR"    | yes?          | ?                       |"marginal log odds ratio"         |
|       | "MPORC"   | yes?          | ?                       |"conditional log odds ratio"      |
|       | "MRPETO"  | yes?          | ?                       |"conditional log odds ratio estimated with Peto's method |
| lnRR  | "MPRR"    | yes?          | ?                       | "marginal log-risk ratio"|
|       | "MPRD"    | yes?          | ?                       | "marginal risk difference" |

# Zr options

You can also calculate point biserial correlation coefficient "RPB" and biserial correlation coefficient "RBIS" but these return an estimate of 'r' and should not be analyzed directly in a meta-analytic model

| class | `escalc` | Comparable to standard? | Details                    |
|-------|----------|-------------------------|----------------------------|
|Zr   | "ZBP"       | Yes                     | "point biserial correlation coefficient directly to Zr" |
|     | "ZBIS"   | Yes                        |  "biserial correlation coefficient directly to Zr" |


## Partial and semi-partial correlations??
*NOT SURE IF WE SHOULD INCLUDE THIS...* This seems to be for regression model coefficients but I know that's risky...Takes R2 too?

What do we do about these?

## Coefficients of determination ($R^2$)

??? Is this wise ?? 

# Other effect sizes

## Individual groups in respect to a dichotomous dependent variable

For example, % of a population that is infected? Or percent of diet?

*PLAIN ENGLISH EXAMPLE*

| `escalc` | Input                      | Name  | Recommended |
|----------|----------------------------|----------|-------------|
| "PLN"   |ni=sample size; xi=proportion| "log-transformed proportion". | ? |   
| "PLO"   |ni=sample size; xi=proportion| "logit-transformed proportion". | ? |   
| "PRZ"   |ni=sample size; xi=proportion| "probit-transformed proportion". | ? |   
| "PRZ"   |ni=sample size; xi=proportion| "probit-transformed proportion". | ? |   


## Individual groups with an event count

For example, % of a population that is infected? Or number of times attacked/affected?

*PLAIN ENGLISH EXAMPLE*

| `escalc` | Input                      | Name  | Recommended |
|----------|----------------------------|----------|-------------|
| "IRLN"   |ti=total person-times at risk; xi=n events| "log-transformed incidence rate". | ? |   
| "IRS"   |ti=total person-times at risk; xi=n events| "square root transformed incidence rate". | ? |   
| "IRFT"   |ti=total person-times at risk; xi=n events| "Freeman-Tukey transformed incidence rate". | ? |   


