project:
  type: website
  output-dir: docs

website:
  title: "User's manual to effect sizes"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: About this tutorial
      - getting_started.qmd
      - href: overview.qmd
        text: Overview of effect sizes
      - href: effect_size_assumptions.qmd
        text: Effect size assumptions & interpretations
      - section: "Extraction challenges"
        contents:
        - href: universal_challenges.qmd
          text: Universal challenges
        - href: smd_extraction_challenges.qmd
          text: Continuous outcome with discrete predictor      
        - href: lnOR_extraction_challenges.qmd
          text: Discrete outcome with discrete predictor
        - href: Zr_extraction_challenges.qmd
          text: Continuous outcome with continuous predictor
      - href: effect_size_conversions.qmd
        text: Converting between effect sizes
      - section: "Appendix"
        contents:
        - escalc_cheatsheet.qmd
        - non_gaussian_responses.qmd
        - organizing_extractions.qmd
        - formulas.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

