project:
  type: website
  output-dir: docs

website:
  title: "User's guide to effect sizes"
  sidebar:
    title: "User's guide to effect sizes"
    logo: /cossee_logo.png
    logo-href: https://cossee.org/
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: About this tutorial
      - href: 1-effect-size-overview.qmd
        text: Overview of effect sizes
      - href: 2-assumptions-interpretations.qmd
        text: Effect size assumptions & interpretations
      - section: "Extracting effect sizes"
        contents:
        - href: 3-starting-extraction.qmd
          text: Getting started
        - href: 4-universal-challenges.qmd
          text: Universal challenges
        - href: 5-smd-challenges.qmd
          text: Continuous outcome with discrete predictor      
        - href: 6-lnOR-challenges.qmd
          text: Discrete outcome with discrete predictor
        - href: 7-Zr-challenges.qmd
          text: Continuous outcome with continuous predictor
      - href: 8-converting-effect-sizes.qmd
        text: Converting between effect sizes
      - section: "Appendix"
        contents:
        - 9-escalc-cheatsheet.qmd
        - 10-simulating-non-gaussian-responses.qmd
        - 11-organizing-extractions.qmd
      # - href: https://cossee.org/
      #   text: "<img src='/cossee_logo.png' width='64' height='64' style='margin-right: 1px; vertical-align: middle;'>"
      - href: https://github.com/ejlundgren/effect_size_tutorial/issues
        text: "<i class='bi bi-github'></i> Did we miss something? Submit an issue"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    df-print: kable

editor: visual

