project:
  type: website
  output-dir: docs

website:
  title: "A user's guide to effect sizes"
  sidebar:
    title: "A user's guide to effect sizes"
    logo: /cossee_logo.png
    logo-href: https://cossee.org/
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: About this tutorial
      - href: 0-to-do-list.qmd
        text: TO DO LIST 🤠🤠🤠 
      - href: 1-effect-size-overview.qmd
        text: Overview of effect sizes & their flavors
      - section: "Effect size assumptions & interpretation"
        contents:
        - href: 2.0-assumptions-interpretations.qmd
          text: Effect sizes are tiny models
        - href: 2.1-SMD-assumptions.qmd
          text: Continuous outcomes with discrete predictors
        - href: 2.2-lnOR-assumptions.qmd
          text: Discrete outcomes with discrete predictors
        - href: 2.3-Zr-assumptions.qmd
          text: Continuous predictors
      - section: "Extracting effect sizes"
        contents:
        - href: 3.0-starting-extraction.qmd
          text: Getting started
        - href: 3.1-universal-challenges.qmd
          text: Universal challenges
        - href: 3.2-smd-challenges.qmd
          text: Continuous outcome with discrete predictors  
        - href: 3.3-lnOR-challenges.qmd
          text: Discrete outcome with discrete predictors
        - href: 3.4-Zr-challenges.qmd
          text: Continuous predictors
      - href: 4-converting-effect-sizes.qmd
        text: Converting between effect sizes
      - section: "Appendix"
        contents:
        - 5-escalc-cheatsheet.qmd
        - 6-simulating-non-gaussian-responses.qmd
        - 7-organizing-extractions.qmd
      # - href: https://cossee.org/
      #   text: "<img src='/cossee_logo.png' width='64' height='64' style='margin-right: 1px; vertical-align: middle;'>"
      - href: https://github.com/ejlundgren/effect_size_tutorial/issues
        text: "<i class='bi bi-github'></i> Did we miss something? Submit an issue"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

