---
title: "Getting started"
subtitle: ""
date: "`r Sys.Date()`"
format: 
  html:
    toc: true
    toc-location: right
    toc-depth: 6
    toc-float: true
    toc-expand: true
    toc-title: "**CONTENTS**"
    output-file: "getting_started.html"
    # embed-resources: true
    # code-fold: true
    code-link: true
    code-tools: true
    # number-sections: false
    # bibliography: ./bib/ref.bib
    fontsize: "10"
    mainfont: "Helvetica"
    monofont: "Fira Code"
    # fontcolor: ""
    page-layout: article
    code-overflow: wrap
    df_print: paged
    theme: cosmo
    code-line-numbers: false
    grid:
      margin-width: 250px
crossref:
  fig-title: Figure     # (default is "Figure")
  tbl-title: Table     # (default is "Table")
  title-delim: "—"     # (default is ":")
  fig-prefix: Fig.     # (default is "Figure")
  tbl-prefix: Table.   # (default is "Table")
editor_options: 
  chunk_output_type: console
execute:
  warning: false
  message: false
  tidy: true
bibliography: references.bib
---

```{r}
#| eval: true
#| echo: false
#| out-width: "70%"

rm(list = ls())
library("metaDigitise")
library("ggplot2")
library("data.table")
library("ggpattern")
library("patchwork")
library("metafor")
library("dplyr")
library("broom")
library("broom.mixed")
library("simplermarkdown")
library("crayon")

# Source our custom functions:
source("scripts/functions/eff_size.R")
source("scripts/functions/convert_effect_sizes.R")

```



# Other resources for conducting a meta-analysis

**WORKFLOW FIGURE on conducting a meta-analysis**

While we wrote this tutorial to be exhaustive on how to extract data for effect sizes—and how to understand effect sizes more generally-there are many other dimensions to conducting a meta-analysis. Here are some of our favorite tutorials and papers, that start with the inception of a meta-analytic project (question formation, scoping, literature search and screening) and proceed through every step of the process:

| Step                          | Reference            | URL   |
|-------------------------------|----------------------|-------|
| Formulating a question        |                      |       |
| Literature search & screening | Lagisz; Foo          | XXXXX |
| Database design               |                      |       |
| Extraction                    | Yours truly          | XXXXX |
| Random effects                |                      |       |
| Modeling                      |                      |       |
| Publication bias              | Nakagawa et al. 2022 |       |
| Reporting guidelines          |                      |       |

# Data extraction planning

## Getting started

The first step to doing the data collection for a meta-analysis is to have a solid and clear question, a screened body of literature, and clear decision trees for what data to extract. We recommend doing pilot extractions (of \~10%) of your screened literature to estimate the total number of anticipated effect sizes. Moreover, we recommend categorizing and calculating the distribution of *extraction challenges* during this stage. By extraction challenges, we mean data that is presented in formats that are difficult to convert to effect sizes-the challenges that this tutorial will help you tackle.

Some extraction challenges, while solvable, introduce assumptions or potential error. If these extraction challenges (such as model estimates) are a minimal portion of a very large dataset, then you can justifiably decide not to extract them. However, if these difficult cases are common, if there are relatively few papers, or if you believe these types of data are *non-randomly* distributed in your dataset (e.g., often occur in papers from certain geographic regions, time periods, etc), then you may want to decide *a priori* to extract them.

This can be done after initial extraction as well, if you took record of the studies that were excluded because they were unextractable. For example, if only 5% of your dataset comes from African countries and 50% of that data was not extractable, we think it would be justifiable to expand your extraction criteria to other data types—though this should be done to articles from all geographic regions, not just Africa.

## Tools for extracting data from figures

If you're lucky, some of the data extraction for a meta-analysis can come directly from summary statistics (mean, sample size, standard deviation, etc) reported in tables or the main text of the papers you're extracting. However, you'll find that the majority of data extraction will be directly from figures. In these cases, you'll employ a variety of tools to extract data from figures.

We do not here discuss the mechanics of these tools but we will describe them and their advantages, briefly, here.

**Add links to tutorials or the webpages**

| Extraction tool | Environment | log-axes | Auto-conversion | Free-form extraction | Built-in reproducibility |
|------------|------------|------------|------------|------------|------------|
| `metaDigitise()` | R | yes | SE/IQR/CIs $\rightarrow$ SD | No | Yes |
| `WebPlotDigitizer` | Web/Desktop | yes | No | Yes | No |
| `ImageJ` | Desktop | no | No | Yes | No |

An analysis (Hrobjartsson et al 2007) found that data extraction errors were prolific in meta-analysis, leading to considerable bias. For that reason, we highly recommend that researchers use transparent workflows for data extraction. This includes saving screenshots of figures, preferably along with extraction points (which is automatically done by `metaDigitise()`) in folders that link directly to the final dataset.

We also note that many AI tools, such as NotebookLM, are capable of extracting data from figures. However, utilizing these tools still requires that researchers maintain reproducible and transparent workflows and understand *what* data to extract.
