---
title: "Effect sizes in meta-analysis"
subtitle: "'A soup to nuts' tutorial for the meta-analyst"
date: today
author:
  - name: Erick J Lundgren
  - name: Eduardo S A Santos
  - name: Santiago Ortega
  - name: Malgorzata Lagisz
  - name: Sage Raymond
  - name: Kyle Morrison
  - name: Josh Pritchard Cairns
  - name: Renato?
  - name: Alfredo Sanchez?
  - name: Daniel Noble?
  - name: Jonas Trepel
  - name: Eamonn Wooster
  - name: Ayumi Mizuno
  - name: Iwo Gross
  - name: Wolfgang??
  - name: Shinichi Nakagawa
format: 
  html:
    toc: true
    toc-location: right
    toc-depth: 6
    toc-float: true
    toc-expand: true
    toc-title: "**Page Contents**"
    output-file: "index.html"
    # embed-resources: true
    # code-fold: true
    code-link: true
    code-tools: true
    # number-sections: false
    # bibliography: ./bib/ref.bib
    fontsize: "10"
    mainfont: "Helvetica"
    monofont: "Fira Code"
    # fontcolor: ""
    page-layout: article
    code-overflow: wrap
    df_print: paged
    theme: cosmo
    code-line-numbers: false
    grid:
      margin-width: 250px
crossref:
  fig-title: Figure     # (default is "Figure")
  tbl-title: Table     # (default is "Table")
  title-delim: "—"     # (default is ":")
  fig-prefix: Fig.     # (default is "Figure")
  tbl-prefix: Table.   # (default is "Table")
editor_options: 
  chunk_output_type: console
execute:
  warning: false
  message: false
  tidy: true
bibliography: references.bib
csl: ecology.csl
---

```{r}
#| eval: true
#| echo: false
#| out-width: "70%"

rm(list = ls())

if(!requireNamespace("metatools")) {
  pak::pak("ejlundgren/metatools")
}
library("metatools")

library("ggplot2")
library("data.table")
library("ggpattern")
library("patchwork")
library("metafor")
library("dplyr")
library("broom")
library("broom.mixed")
library("simplermarkdown")
library("crayon")

```

# Introduction {#sec-introduction}

Meta-analysis has grown to be one of the powerful methods in science. By extracting data from across the literature, a meta-analyst can answer age-old questions at scales previously unimaginable. Moreover, meta-analysis can test for and correct publication bias and can thus not only control for biases in the literature base but provide a bridge between empirical questions (i.e., what is) and metascientific questions (e.g., how scientists construct knowledge).

Meta-analysis can be really hard. Meta-analytic methods continue to proliferate, with new effect sizes, models, and methods being published constantly. The literature has become a minefield of articles and tutorials that can be bewildering for even the most experienced meta-analyst.  

We here present a living tutorial to navigating this methodological tempest, with particular emphasis on understanding effect sizes and extracting them from a variety of data formats. This tutorial is maintained by the [Collaboration for Open Science and Synthesis in Ecology and Evolution](https://cossee.org/) at the University of Alberta, which is led by Professor Shinichi Nakagawa—one of the principle developers of new meta-analytic methods. While many of the examples in this tutorial derive from our experiences in ecology and evolution, which is rife with messy data, we believe the contents are applicable broadly.

We hope that this tutorial, by integrating tips and tricks and statistical know-how from across the decades and into the future, can increase the consistency, reliability, and reproducibility of meta-analytic research.

**Should we add more of an overview of what meta-analysis is?**

# Voyaging among the ghosts of data past  {#sec-voyagers}

Meta-analyses are powerful. But they are full of tedium. And dealing with the challenges that we describe in this tutorial (hopefully in plain english) can be overwhelming.

Yet there is something beautiful and very human about doing a meta-analysis. You encounter the heartwork and hardwork of dozens or hundreds or thousands of fellow human beings. Stories from last year or 50 years ago, from people exploring, observing, experimenting, and trying to understand our universe.

These voyagers left us breadcrumbs. Sometimes as simple as a mean and a standard deviation. Sometimes as complex as some strange contour plot drawn on a piece of graph paper and scanned in 1975. Extracting their data summaries (or finding their raw datasets) brings their work to life and allows us to continue their quests.

While you struggle to deal with all the strange and bizarre and difficult and annoying decisions these voyagers sometimes made to communicate their tales, remember to feel compassion and awe for the work that came before us--these efforts to describe the mysteries of our world.

# How to use this tutorial  {#sec-how-to}

We begin by discussing the dominant [effect size types](1-effect-size-overview.qmd), their numeric assumptions, and how to interpret them. We then discuss the nuts and bolts of planning data [extraction](3.0-starting-extraction.qmd). 

We then go into detail about [universal challenges](3.1-universal-challenges.qmd) in extracting and calculating effect sizes, including the many odd and unusual data formats that you may uncover. We conclude with a discussion of how to [convert](4-converting-effect-sizes.qmd) between effect size types. In the appendix you'll find additional helpful material, including descriptions of [less common](5-less-common-effect-sizes.qmd), a [cheatsheet](6-escalc-cheatsheet.qmd) for the many options available in the workhorse of effect size calculation: `metafor`'s `escalc` function [@Viechtbauer2010-uq].

This tutorial is viewable as a webpage or you can clone the repo and run the .qmd files interactively. This tutorial corresponds with the cheatsheets provided here *XXXXXX.*

This tutorial is based on an `R` workflow and assumes that the users have a basic understanding of `R`.

# A living tutorial  {#sec-living-tutorial}

This tutorial is a living document. As such, please help us keep it alive and useful. If we missed anything, if we made an error, or overlooked an extraction challenge, please file an Issue on our github page [here](https://github.com/ejlundgren/effect_size_tutorial/issues).
